site_name: Correlator Docs

theme:
  name: "material"
  palette:
    scheme: slate

plugins:
  - mkdocstrings

nav:
  - Home: index.md
  - Features: features.md
  - Quick start: quickstart.md
  - Concepts:
      - Frontend engine: frontend.md
      - Modules: modules.md
      - Event system: event-system.md
      - Stack: stack.md
  - Reference: reference.md
  - Included front-end processors:
      - Syslog server: syslog-server.md
      - Logfile processor: logfile-processor.md
  - Included Modules:
      - OpenSSH login: sshd-module.md
      - Report: report-module.md
  - Included Event Handlers:
      - Logback: logback-handler.md
      - CSV: csv-handler.md
      - E-Mail: email-handler.md
      - SMS: sms-handler.md
  - Why: why.md
