site_name: Correlator Docs

theme:
  name: "material"
  palette:
    scheme: slate

plugins:
  - mkdocstrings

nav:
  - Home: index.md
  - Installation: installation.md
  - Quick start: quickstart.md
  - Architecture: architecture.md
  - Why: why.md
