site_name: Correlator Docs

theme:
  name: "material"
  palette:
    scheme: slate

plugins:
  - mkdocstrings

nav:
  - Home: index.md
  - Features: features.md
  - Why: why.md
  - Quick start: quickstart.md
  - Architecture: architecture.md
  - OpenSSH login module: sshd.md
  - Reference: reference.md
  - Modules:
      - OpenSSH login: sshd-module.md
      - Report: report-module.md
  - Event Handlers:
      - Logback: logback-handler.md
      - CSV: csv-handler.md
      - E-Mail: email-handler.md
      - SMS: sms-handler.md