[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "Correlator"
description = "log analysis system"
readme = "README.md"

version = "0.0.1"
dependencies = [
    "iso8601",
    "Mako",
    "MarkupSafe"
]

[tool.setuptools.packages.find]
where = ["."]  # ["."] by default
include = ["Correlator*"]  # ["*"] by default
# exclude = ["mypackage.tests*"]  # empty by default
namespaces = false  # true by default

[project.scripts]
syslog_server = "Correlator.syslog:main"
process_idm_logfile = "Correlator.logfile:main"
