# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import frontend_record_pb2 as frontend__record__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in frontend_record_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FrontEndInputStub(object):
    """package Sources;

    Interface exported by the server.

    For the TCP Syslog Source (in the Sources/TCP_Syslog directory):

    python -m grpc_tools.protoc -I../../proto --python_out=. --grpc_python_out=. ../../proto/frontend_record.proto

    For the input processor: (in the main source directory):

    python -m grpc_tools.protoc -Iproto --python_out=. --grpc_python_out=. proto/frontend_record.proto

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessRecord = channel.stream_unary(
                '/FrontEndInput/ProcessRecord',
                request_serializer=frontend__record__pb2.Record.SerializeToString,
                response_deserializer=frontend__record__pb2.Result.FromString,
                _registered_method=True)


class FrontEndInputServicer(object):
    """package Sources;

    Interface exported by the server.

    For the TCP Syslog Source (in the Sources/TCP_Syslog directory):

    python -m grpc_tools.protoc -I../../proto --python_out=. --grpc_python_out=. ../../proto/frontend_record.proto

    For the input processor: (in the main source directory):

    python -m grpc_tools.protoc -Iproto --python_out=. --grpc_python_out=. proto/frontend_record.proto

    """

    def ProcessRecord(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FrontEndInputServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessRecord': grpc.stream_unary_rpc_method_handler(
                    servicer.ProcessRecord,
                    request_deserializer=frontend__record__pb2.Record.FromString,
                    response_serializer=frontend__record__pb2.Result.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'FrontEndInput', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('FrontEndInput', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FrontEndInput(object):
    """package Sources;

    Interface exported by the server.

    For the TCP Syslog Source (in the Sources/TCP_Syslog directory):

    python -m grpc_tools.protoc -I../../proto --python_out=. --grpc_python_out=. ../../proto/frontend_record.proto

    For the input processor: (in the main source directory):

    python -m grpc_tools.protoc -Iproto --python_out=. --grpc_python_out=. proto/frontend_record.proto

    """

    @staticmethod
    def ProcessRecord(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/FrontEndInput/ProcessRecord',
            frontend__record__pb2.Record.SerializeToString,
            frontend__record__pb2.Result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
