#!/bin/bash

# "wrapper Script" to start both rsyslog and ssh in a Docker container.
# rsyslog is required to forward log data generated by ssh to Correlator.

# https://docs.docker.com/config/containers/multi-service_container/

LOGSOCKET=/dev/log
RETRIES=5

function error_exit () {
	echo "** Initialization of rsyslog plus secure shell failed"
	exit 1
}

echo "** Starting rsyslog"

/usr/sbin/rsyslogd -n &
rsyslog_pid=$!

# wait for /dev/log

COUNT=1

while true
do
  echo "** Waiting for log socket ${LOGSOCKET}"
  sleep 1

  if [ -S ${LOGSOCKET} ]; then
        break
  fi
  COUNT=expr`${COUNT} + 1`

  if [ "${COUNT}" -eq "${RETRIES}" ]; then
    echo "** Retry count exceeded (${RETRIES})"
    error_exit
  fi
done

echo "** Starting sshd"

# Create privilege separation directory if it does not exist

if [ ! -d /run/sshd ]; then
 mkdir /run/sshd
fi

/usr/sbin/sshd -D &
sshd_pid=$!

echo "** Initialization of rsyslog plus secure shell complete. Waiting for either to exit"

wait -p job_id -n ${sshd_pid} ${rsyslog_pid}

if [ "${job_id}" = ${sshd_pid} ]; then
  echo "** ERROR: sshd died. Shutting down"
else
  echo "** ERROR: rsyslogd died. Shutting down"
fi

exit $?
