# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mediator.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'mediator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emediator.proto\"b\n\x0cSourceRecord\x12\x11\n\ttenant_id\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x04\x12\x0c\n\x04type\x18\x03 \x01(\x05\x12\x11\n\tsource_id\x18\x04 \x01(\t\x12\x0b\n\x03obj\x18\x05 \x01(\x0c\"-\n\x0b\x45ventRecord\x12\x11\n\ttenant_id\x18\x01 \x01(\t\x12\x0b\n\x03obj\x18\x02 \x01(\x0c\"\'\n\x06Result\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x07\n\x05\x45mpty2\x89\x01\n\x08Mediator\x12.\n\x10StreamSourceData\x12\r.SourceRecord\x1a\x07.Result\"\x00(\x01\x12(\n\rDispatchEvent\x12\x0c.EventRecord\x1a\x07.Result\"\x00\x12#\n\x0e\x43onnectionTest\x12\x06.Empty\x1a\x07.Result\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mediator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SOURCERECORD']._serialized_start=18
  _globals['_SOURCERECORD']._serialized_end=116
  _globals['_EVENTRECORD']._serialized_start=118
  _globals['_EVENTRECORD']._serialized_end=163
  _globals['_RESULT']._serialized_start=165
  _globals['_RESULT']._serialized_end=204
  _globals['_EMPTY']._serialized_start=206
  _globals['_EMPTY']._serialized_end=213
  _globals['_MEDIATOR']._serialized_start=216
  _globals['_MEDIATOR']._serialized_end=353
# @@protoc_insertion_point(module_scope)
